idf_component_register(
    SRCS "ride_on_dash.c"
        "../app/app.c"
        "../app/ui/navigator.c"
        "../app/ui/ui_helpers.c"
        "../app/ui/view/home/presenter_home.c"
        "../app/ui/view/home/view_home.c"
        "../app/ui/view/accessory/model_accessory.c"
        "../app/ui/view/accessory/presenter_accessory.c"
        "../app/ui/view/accessory/view_accessory.c"
        "../app/ui/view/color_picker/model_color_picker.c"
        "../app/ui/view/color_picker/presenter_color_picker.c"
        "../app/ui/view/color_picker/view_color_picker.c"
        "../bridge/bridge.c"
        "../config/_color.c"
        "../system/_system.c"
        "../system/controller/led_controller.c"
        "../system/driver/led_driver.c"
    INCLUDE_DIRS "."
        "../app"
        "../app/ui"
        "../app/ui/view/home"
        "../app/ui/view/accessory"
        "../app/ui/view/color_picker"
        "../bridge"
        "../config"
        "../system"
        "../system/controller"
        "../system/driver"
    )
